name: 'Issue Management Action'
description: 'Automatically assigns and moves Issues that are linked to Pull Requests'
author: 'TorqIT'
icon: move
inputs:
  token:
    required: true
    description: 'GitHub token. In an Action, use secrets.GITHUB_TOKEN'
  fromColumnId:
    required: true
    description: 'The project column in which to look for issues'
  toColumnId:
    required: true
    description: 'The project column to move issues to'
runs:
  using: 'node16'
  main: 'dist/index.js'
