name: 'Issue Management Action'
description: 'Automatically assigns and moves Issues that are linked to Pull Requests'
author: 'TorqIT'
branding:
  icon: 'move'
  color: 'green'
inputs:
  token:
    required: true
    description: 'GitHub token. In an Action workflow, use secrets.GITHUB_TOKEN'
  projectNumber:
    required: true
    description: 'Project number. Can be found in the URL of your project (i.e. https://github.com/orgs/<your-org>/projects/<project-number>)'
runs:
  using: 'node16'
  main: 'dist/index.js'
