name: 'Issue Management Action'
description: 'Automatically assigns and moves Issues that are linked to Pull Requests'
author: 'TorqIT'
branding:
  icon: 'move'
  color: 'green'
inputs:
  token:
    required: true
    description: GitHub token. See README for details on how to generate this.
  projectNumber:
    required: true
    description: Project number. Can be found in the URL of your project (i.e. https://github.com/orgs/<your-org>/projects/<project-number>)
  testers:
    required: false
    description: (Optional) comma-separated list of tester usernames. When a review is requested from one of these users, the linked issues will be moved to a "Test" status (a status containing this word must exist in the project)
runs:
  using: 'node16'
  main: 'dist/index.js'
