name: 'build-test'
on:
  pull_request:
    types: synchronize

jobs:
  pull_requests:
    permissions:
      id-token: read
      repository-projects: read
      issues: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run all

      - name: Run test
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectNumber: 10
