name: 'build-test'
on:
  pull_request:
    types: synchronize

jobs:
  pull_requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - name: Build
        run: |
          npm install
          npm run all

      - name: Run test
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectNumber: 10
