name: 'Run action on PRs to test the action'

on:
  pull_request:
    types: review_requested

jobs:
  pull_requests:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          npm install
          npm run all

      - name: Run
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromColumnIds: 17997143,17997146
          toColumnId: 17997150
