name: 'build-test'
on:
  pull_request:
    types: synchronize

jobs:
  pull_requests:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          ls -l
          npm install
          npm run all

      - name: Run test
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectNumber: 10
